name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: docker login 
      run: docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
    - name: tag image 
      run: docker tag my-image-name:$(date +%s) ${{secrets.REGISTRY_USERNAME}}/resume
    - name: push image to dockerhub
      run: docker push ${{secrets.REGISTRY_USERNAME}}/resume
