#name of the workflow

name: my first action

#workflow trigger

on: 
    push:
        branches: [ "main"]
    pull_request: 
        branches: [ "main"]
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: test
              run: ls
    scan:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: scan  the code
              run: echo scan
            - name: scan
              run: echo scan    
    unittest:
        needs: scan
        runs-on: ubuntu-latest
        steps:
                    - name: unittest  the code
                      run: pwd 
                    - name: unittest
                      run: ls  

