#name of the workflow

name: my first action

#workflow trigger

on: 
    push:
        branches: [ "main"]
    pull_request: 
        branches: [ "main"]
    workflow_dispatch:
        
permissions:
            id-token: write
            contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            
            - name: Login to Azure Container Registry
              run: |
                docker login -u ${{ secrets.acr_user }} -p ${{ secrets.acr_pass }} ${{ secrets.acr_host }}
            - name: Build and Push Image
              run: |
                docker build -t ${{ secrets.acr_host}}/my-image:latest .
             # Scan the Docker image for vulnerabilities using Trivy
            - name: Scan image with Trivy
              uses: aquasecurity/trivy-action@master
              with:
                    image-ref: ${{ secrets.acr_host}}/my-image:latest
                    severity: CRITICAL
                    exit-code: '0'  # Fail the build if high or critical vulnerabilities are found
            - name: docker push image
              run: |
                docker push ${{ secrets.acr_host }}/my-image:latest
    scan:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: scan  the code
              run: echo scan
            - name: scan
              run: echo scan    
    unittest:
        needs: scan
        runs-on: ubuntu-latest
        steps:
                    - name: unittest  the code
                      run: pwd 
                    - name: unittest
                      run: ls  

